version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: > 
      sh -c "python manage.py collectstatic --no-input &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    ports:
      - ${PORT:-8000}:8000
    env_file:
      - .env