# Generated by Django 4.2.3 on 2023-07-28 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyhistory',
            name='item_id',
            field=models.TextField(default='old'),
            preserve_default=False,
        ),
    ]
